

logbook:
  filter.enabled: true
  format.style: json
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
  write:
    category: http.traffic
    level: INFO

# TODO: find out how we can disable the service tomcat completely, without also disabling
# the management one. Setting the server port to -1 still starts up a tomcat (judging by
# the logs), just non-reachable.
#
#spring.main.web_environment: false

server.port: -1
management.port: 7979

logging.pattern.console: "%date {%level} [%thread] [%X{X-FLOW-ID}] [%logger] %message%n"
logging.pattern.file: "%date {%level} [%thread] [%X{X-FLOW-ID}] [%logger] %message%n"
