tokens:
    token-configuration-list:
        - tokenId: producer
          scopes:
              - uid
              - warehouse-allocation.read
#        - tokenId: nakadi
#          scopes: nakadi.event_stream.write